const elements = {
  body: document.body,
  toggleButton: document.querySelector('.toggle-button'),
  themeName: document.getElementById('theme-name'),
  hamburger: document.querySelector('.hamburger'),
  menu: document.querySelector('.hamburger-menu'),
  bars: document.querySelectorAll('.bar'),
  tabListEl: document.getElementById('tab-list'),
  tabPanelsEl: document.getElementById('tab-panels'),
  addTabBtn: document.getElementById('add-tab'),
  panelTmpl: document.getElementById('panel-template'),
  navButtons: document.querySelectorAll('.nav-btn'),
  outputView: document.getElementById('output-view'),
  outputBtn: document.getElementById('output-btn')
};

function switchTheme() {
  if (!elements.toggleButton || !elements.themeName) return;

  elements.body.classList.toggle('dark-mode');
  elements.toggleButton.classList.toggle('active');

  const isDarkMode = elements.body.classList.contains('dark-mode');
  elements.themeName.textContent = isDarkMode ? 'dark' : 'light';
  try {
    localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
  } catch (error) {
    console.error('Failed to save theme:', error);
  }
}

function initTheme() {
  if (!elements.themeName) return;

  let savedTheme = null;
  try {
    savedTheme = localStorage.getItem('theme');
  } catch (error) {
    console.error('Failed to load theme:', error);
  }

  if (savedTheme === 'dark' && elements.toggleButton) {
    elements.body.classList.add('dark-mode');
    elements.toggleButton.classList.add('active');
    elements.themeName.textContent = 'dark';
  } else {
    elements.themeName.textContent = 'light';
  }
}

function toggleHamburgerMenu() {
  if (!elements.hamburger || !elements.menu || !elements.bars) return;

  elements.hamburger.classList.toggle('open');
  elements.menu.classList.toggle('open');
  elements.bars.forEach(bar => bar.classList.toggle('open'));
}

function initNavButtons() {
  if (!elements.navButtons || !elements.outputView) return;

  elements.navButtons.forEach(button => {
    button.addEventListener('click', () => {
      elements.outputView.textContent = `Navigated to: ${button.textContent || 'Unknown'}`;
    });
  });
}

function generateOutputHTML() {
  if (!elements.outputView) return;

  const tabData = tabs.map(t => ({
    id: t.id,
    title: t.tabEl.textContent || '',
    notes: t.panelEl.querySelector('.panel-notes')?.value || ''
  }));

  const tabCount = Math.min(tabData.length, 5);
  const tabsToInclude = tabData.slice(0, tabCount);

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Tabs</title>
</head>
<body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5;">
    <h1 style="color: #333; font-size: 2rem; text-align: center;">Generated Tabs</h1>
    <div style="display: flex; flex-direction: column; gap: 10px; max-width: 600px; margin: 0 auto;">
`;

  tabsToInclude.forEach((tab, index) => {
    html += `
        <div style="border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px; background: #fff;">
            <h2 style="font-size: 16px; color: #333; margin: 0 0 10px 0;">${tab.title}</h2>
            <p style="font-size: 13px; color: #666; margin: 0;">${tab.notes || 'No notes'}</p>
        </div>
    `;
  });

  html += `
    </div>
    <footer style="text-align: center; margin-top: 20px; color: #666;">
        <p>Generated by April-Jane O'Loughlin, 22453908, 29/8/25</p>
    </footer>
</body>
</html>`;

  elements.outputView.textContent = html;
}

const tabs = [];
const MAX_TABS = 15;
let nextNum = 1;

function numFromId(id) {
  const n = parseInt(id.split('-').pop() || '0', 10);
  return Number.isFinite(n) ? n : 0;
}

function createTab(title = `Tab ${nextNum}`, notes = '') {
  if (!elements.tabListEl || !elements.tabPanelsEl || !elements.panelTmpl || !elements.addTabBtn) return null;

  if (tabs.length >= MAX_TABS) {
    alert(`You can only have up to ${MAX_TABS} tabs.`);
    if (elements.outputView) elements.outputView.textContent = `Error: Maximum ${MAX_TABS} tabs reached`;
    return null;
  }

  const id = `tab-${nextNum}`;
  const panelId = `panel-${id}`;
  nextNum++;

  const li = document.createElement('li');
  li.className = 'tab';
  li.setAttribute('role', 'presentation');

  const btn = document.createElement('button');
  btn.className = 'tab-btn';
  btn.setAttribute('role', 'tab');
  btn.id = id;
  btn.setAttribute('aria-controls', panelId);
  btn.setAttribute('aria-selected', 'false');
  btn.textContent = title;

  const actions = document.createElement('div');
  actions.className = 'tab-actions';

  const renameBtn = document.createElement('button');
  renameBtn.className = 'icon-btn';
  renameBtn.title = 'Rename';
  renameBtn.textContent = '✎';

  const closeBtn = document.createElement('button');
  closeBtn.className = 'icon-btn';
  closeBtn.title = 'Close';
  closeBtn.textContent = '×';

  actions.append(renameBtn, closeBtn);
  li.append(btn, actions);
  elements.tabListEl.appendChild(li);

  const panel = document.createElement('div');
  panel.className = 'panel';
  panel.id = panelId;
  panel.setAttribute('role', 'tabpanel');
  panel.setAttribute('aria-labelledby', id);
  panel.setAttribute('aria-hidden', 'true');

  const node = elements.panelTmpl.content.cloneNode(true);
  panel.appendChild(node);
  elements.tabPanelsEl.appendChild(panel);

  const titleInput = panel.querySelector('.panel-title-input');
  const notesTextarea = panel.querySelector('.panel-notes');
  if (titleInput && notesTextarea) {
    titleInput.value = title;
    notesTextarea.value = notes;
  }

  const item = { id, tabEl: btn, panelEl: panel, containerEl: li };
  tabs.push(item);

  btn.addEventListener('click', () => {
    selectTab(id);
    if (elements.outputView) elements.outputView.textContent = `Selected tab: ${title}`;
  });
  btn.addEventListener('keydown', (e) => {
    const idx = tabs.findIndex(t => t.id === id);
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      const nxt = tabs[Math.min(idx + 1, tabs.length - 1)];
      if (nxt) {
        nxt.tabEl.focus();
        selectTab(nxt.id);
        if (elements.outputView) elements.outputView.textContent = `Selected tab: ${nxt.tabEl.textContent}`;
      }
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      const prv = tabs[Math.max(idx - 1, 0)];
      if (prv) {
        prv.tabEl.focus();
        selectTab(prv.id);
        if (elements.outputView) elements.outputView.textContent = `Selected tab: ${prv.tabEl.textContent}`;
      }
    }
  });

  renameBtn.addEventListener('click', () => {
    const current = btn.textContent;
    const newTitle = prompt('New tab name:', current || '');
    if (newTitle && newTitle.trim() && titleInput) {
      btn.textContent = newTitle.trim();
      titleInput.value = newTitle.trim();
      saveTabs();
      if (elements.outputView) elements.outputView.textContent = `Renamed tab to: ${newTitle.trim()}`;
    } else if (newTitle !== null) {
      alert('Tab name cannot be empty.');
      if (elements.outputView) elements.outputView.textContent = `Error: Tab name cannot be empty`;
    }
  });

  closeBtn.addEventListener('click', () => {
    removeTab(id);
    saveTabs();
    if (elements.outputView) elements.outputView.textContent = `Closed tab: ${title}`;
  });

  if (titleInput) {
    titleInput.addEventListener('input', () => {
      btn.textContent = titleInput.value || `Tab ${numFromId(id)}`;
      saveTabs();
      if (elements.outputView) elements.outputView.textContent = `Updated tab title to: ${titleInput.value}`;
    });
  }

  if (notesTextarea) {
    notesTextarea.addEventListener('input', () => {
      saveTabs();
      if (elements.outputView) elements.outputView.textContent = `Updated notes for tab: ${btn.textContent}`;
    });
  }

  selectTab(id);
  saveTabs();
  if (elements.outputView) elements.outputView.textContent = `Created tab: ${title}`;
  return id;
}

function selectTab(id) {
  tabs.forEach(t => {
    const active = t.id === id;
    t.tabEl.setAttribute('aria-selected', `${active}`);
    t.panelEl.setAttribute('aria-hidden', `${!active}`);
  });
}

function removeTab(id) {
  const idx = tabs.findIndex(t => t.id === id);
  if (idx === -1) return;

  const removedNum = numFromId(id);
  const [t] = tabs.splice(idx, 1);
  t.containerEl.remove();
  t.panelEl.remove();

  if (tabs.length === 0) {
    nextNum = 1;
    saveTabs();
    return;
  }

  if (removedNum === nextNum - 1) {
    nextNum = Math.max(1, nextNum - 1);
  }

  const next = tabs[Math.min(idx, tabs.length - 1)];
  if (next) {
    selectTab(next.id);
    next.tabEl.focus();
  }
  saveTabs();
}

function saveTabs() {
  const tabData = tabs.map(t => ({
    id: t.id,
    title: t.tabEl.textContent || '',
    notes: t.panelEl.querySelector('.panel-notes')?.value || ''
  }));
  try {
    localStorage.setItem('tabs', JSON.stringify(tabData));
  } catch (error) {
    console.error('Failed to save tabs:', error);
  }
}

function loadTabs() {
  try {
    const savedTabs = JSON.parse(localStorage.getItem('tabs') || '[]');
    if (savedTabs.length > 0) {
      savedTabs.forEach(tab => createTab(tab.title, tab.notes));
      nextNum = Math.max(...savedTabs.map(t => numFromId(t.id))) + 1;
    } else {
      createTab('Welcome');
    }
  } catch (error) {
    console.error('Failed to load tabs:', error);
    createTab('Welcome');
  }
}

function initialize() {
  if (elements.toggleButton) {
    elements.toggleButton.addEventListener('click', switchTheme);
  }
  if (elements.hamburger) {
    elements.hamburger.addEventListener('click', toggleHamburgerMenu);
  }
  if (elements.addTabBtn) {
    elements.addTabBtn.addEventListener('click', () => createTab());
  }
  if (elements.outputBtn) {
    elements.outputBtn.addEventListener('click', generateOutputHTML);
  }
  initTheme();
  initNavButtons();
  loadTabs();
}

initialize();

